version: '3.8'
services:
  frontend:
    build:
      context: .
      target: frontend-builder
    volumes:
      - ./front_end:/app
    ports:
      - "3000:3000"
    command: npm run dev

  backend:
    build:
      context: .
      target: backend-builder
    volumes:
      - ./back_end:/app
    ports:
      - "88:88"
    command: npm start

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1075773551
    ports:
      - "3304:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
